version: '3'

services:
  nginx:
    container_name: itacwt_nginx
    build:
      context: development/nginx
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/itacwt
    ports:
      - "8088:80"
    depends_on:
      - php-fpm
  php-fpm:
    container_name: itacwt_php-fpm
    build:
      context: development/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/itacwt
    depends_on:
      - database
  database:
    container_name: itacwt_database
    image: postgres:15.1-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: itacwt
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: itacwt
    ports:
      - "5433:5432"
  redis:
    container_name: itacwt_redis
    image: redis:6.0-alpine
    volumes:
      - redis:/data
    ports:
      - "6378:6379"
    command: redis-server --requirepass secret

volumes:
  database:
  redis: